# Streamlit Secrets Configuration Template
# Copy this to .streamlit/secrets.toml and fill in your actual values

[sendgrid]
SENDGRID_API_KEY = "your_sendgrid_api_key_here"
SENDGRID_FROM_EMAIL = "netrates@thehireman.co.uk"

[google_drive]
# Paste the ENTIRE contents of your service account JSON file here
# Each field should be copied exactly as it appears in the JSON
type = "service_account"
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nyour-private-key-here\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@your-project.iam.gserviceaccount.com"
client_id = "your-client-id"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account%40your-project.iam.gserviceaccount.com"